In [2]:
import pandas as pd

df = pd.read_csv('./files/Salaries.csv')

df.head()

C:\Users\wecan\AppData\Local\Temp\ipykernel_15584\2066698830.py:3: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./files/Salaries.csv')

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [4]:
df.shape

(148654, 13)

In [ ]:
# Ustun nomlarini chiqarish
print("Ustun nomlari:", df.columns.tolist())

# Har bir ustunning ma'lumot turini ko'rish
print("\nUstunlardagi ma'lumot turlari:\n", df.dtypes)

Ustun nomlari: ['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay', 'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency', 'Status']
*********

Ustunlardagi ma'lumot turlari:
 Id                    int64
EmployeeName         object
JobTitle             object
BasePay              object
OvertimePay          object
OtherPay             object
Benefits             object
TotalPay            float64
TotalPayBenefits    float64
Year                  int64
Notes               float64
Agency               object
Status               object
dtype: object

In [8]:
katta_yoshlar = df.query("TotalPay > 200000")
katta_yoshlar.shape

(2008, 13)

In [10]:
San_fransisko = df[df['Status'].isin(['FT'])]

San_fransisko.shape

(22334, 13)

In [16]:
pivot = df.pivot_table(values='TotalPay', index='EmployeeName', aggfunc='mean')
pivot

                        TotalPay
EmployeeName
A BERNARD FATOOH       20039.910
A Bernard  Fatooh      23923.620
A Bernard Fatooh       21280.770
A ELIZABETH MARCHASIN  26282.860
A JAMIL NIAZI          87496.210
...                          ...
Zun Jin Zhang He       57820.370
Zuna Luu               52518.080
Zuna T Luu             56121.675
Zuri  Jones            71986.900
Zuri Jones             76628.030

[110811 rows x 1 columns]